appname: "PerlMagpie"
layout: "main"
charset: "UTF-8"
template: "template_toolkit"
session: Cookie

engines:
  session:
    Cookie:
      secret_key: 'PerlIsNotDead'
      default_duration: 608400
      with_request_address: 0
  template:
    template_toolkit:
      # Note: start_tag and end_tag are regexes
      start_tag: '[%'
      end_tag:   '%]'

plugins:
  Auth::Extensible:
    no_default_pages: 1
    no_login_handler: 1
    realms:
      default:
        provider: DBIxClass
   